INSERT INTO [dbo].[BusinessCategory] ([id], [name]) VALUES (NULL, N'Business Support & Supplies')
INSERT INTO [dbo].[BusinessCategory] ([id], [name]) VALUES (NULL, N'Automotive')
INSERT INTO [dbo].[BusinessCategory] ([id], [name]) VALUES (NULL, N'Computers & Electronics')
INSERT INTO [dbo].[BusinessCategory] ([id], [name]) VALUES (NULL, N'Construction & Contractors')
INSERT INTO [dbo].[BusinessCategory] ([id], [name]) VALUES (NULL, N'Education')
INSERT INTO [dbo].[BusinessCategory] ([id], [name]) VALUES (NULL, N'Entertainment')
INSERT INTO [dbo].[BusinessCategory] ([id], [name]) VALUES (NULL, N'Food & Dining')
INSERT INTO [dbo].[BusinessCategory] ([id], [name]) VALUES (NULL, N'Home & Garden')
INSERT INTO [dbo].[BusinessCategory] ([id], [name]) VALUES (NULL, N'Legal & Financial')
INSERT INTO [dbo].[BusinessCategory] ([id], [name]) VALUES (NULL, N'Merchants (Retail)')
INSERT INTO [dbo].[BusinessCategory] ([id], [name]) VALUES (NULL, N'Miscellaneous')
INSERT INTO [dbo].[BusinessCategory] ([id], [name]) VALUES (NULL, N'Personal Care & Services')
INSERT INTO [dbo].[BusinessCategory] ([id], [name]) VALUES (NULL, N'Real Estate')
INSERT INTO [dbo].[BusinessCategory] ([id], [name]) VALUES (NULL, N'Travel & Transportation')
INSERT INTO [dbo].[BusinessCategory] ([id], [name]) VALUES (NULL, N'Manufacturing, Wholesale,
Distribution')